### ISSUE TITLE
[Question] Editing router settings

### ISSUE THREAD

**Issue by steakscience** [geekman/xqrepack#13]
Hi,
Since router settings can be edited via various files exposed in ssh, would it be possible for someone to extend this and build a web GUI to edit the router's settings?

I'm asking because the Xiaomi interface exposes very few settings. And the other end of the spectrum is the OpenWRT port which may take a long time.

**Comment by geekman** [comment]
Yes it is possible, of course. Maybe an easier way to achieve this might be to just replace the current web UI with the stock web UI from OpenWRT. It will take some effort to do and maintain as Xiaomi updates their firmware. xqrepack just does the bare minimum to allow users to access the router's internals, and it's not meant to be an alternative firmware.

**Comment by steakscience** [comment]
Thank you!
