### ISSUE TITLE
Support for Xiaomi AX6000

### ISSUE THREAD

**Issue by mrmaximas** [geekman/xqrepack#19]
It's possible to make? 
thanks!

**Comment by unocerobits** [comment]
Yes, but...
I have modified the patch files to work with hostapd.sh and qcawificfg80211.sh, works and we have webgui translated, IoT network accesible and hosts file perfectly following the xqrepack's fork of [pablocp19](https://github.com/pablocp19/xqrepack/).
But...
I have detected that Internet LED is **always off**, but I have perfect connection:
![image](https://user-images.githubusercontent.com/25344454/207981299-6c866d3a-8c16-476b-938d-21c0478318bc.png)

Also I have problems with Alexas, they don't reach the network, maybe hosts file is filtering.

**Comment by geekman** [comment]
AX6000 should be working, as tested by @unocerobits.

**Comment by unocerobits** [comment]
Great geekman,
With your script, could be possible change to RW (or resize) partitions?
BR
Daniel Voces
***@***.***

**Comment by geekman** [comment]
No, the sizes aren't stored in the squashfs. It's probably defined in the device tree or hardcoded in the kernel.
