### ISSUE TITLE
Syntax error for repack-squashfs.sh 

### ISSUE THREAD

**Issue by cogentcoder** [geekman/xqrepack#2]
I'm getting following error and can someone tell me if I need to edit something in the script file.

```
nitin@lubuntu20:~/Xiaomi_AX3600/Firmware$ fakeroot -- ./repack-squashfs.sh ubifs-root/miwifi_r3600_firmware_f7f3e_1.0.67.bin/img-267845145_vol-ubi_rootfs.ubifs
./repack-squashfs.sh: 8: Syntax error: newline unexpected

```
Thanks!

**Comment by geekman** [comment]
Can you try changing the first line from `/bin/sh` to `/bin/bash` instead?

**Comment by cogentcoder** [comment]
Thanks for your reply. The error was cause because I had the wrong file content in the script(i saved with "save as"). After downloading as zip, I had no problem for the script. For second script (ubinize.sh), I was getting error that mtd-utils is not installed and I installed mtd-utils on my ubuntu and this error also gone and I could generate the bin file successfully.
