### ISSUE TITLE
Future firmware updates

### ISSUE THREAD

**Issue by steakscience** [geekman/xqrepack#20]
After patching the router, can future updates be installed safely?

Also, would installing updates re-enable phone home?

**Comment by geekman** [comment]
> After patching the router, can future updates be installed safely?

Updates can be installed, either repacked or original. Repacked firmware must be installed via SSH, and original firmware updates can be done via the web UI.

The update process should be safe, as it is the same way using an A/B process. In case of any problems, the bootloader can revert to a previous version of the firmware.

> Also, would installing updates re-enable phone home?

Yes. The code that phones home is in the original firmware. The repacked firmware has most of the phone home functionality disabled. I cannot guarantee that there is no phone home code left, but what I'm aware of should be removed.

**Comment by steakscience** [comment]
Thank you!
