### ISSUE TITLE
Issue with repack-squashfs.sh and AX1800

### ISSUE THREAD

**Issue by gabriel-lando** [geekman/xqrepack#23]
Hello, I'm trying to run your scripts to patch the latest version of the AX1800 firmware (1.0.394), but the script repack-squashfs.sh fails.

I'm using the following command: `fakeroot -- ./repack-squashfs.sh ubifs-root/miwifi_rm1800_firmware_47f08_1.0.394.bin/img-793458279_vol-ubi_rootfs.ubifs`

During the script execution, I see this prompt: `Reversed (or previously applied) patch detected!  Assume -R? [n]`. Any option I select will fail.

If I use the default option (No), it will ask me to "Apply anyway". If I chose "No", it would ignore and finish the script.
If I chose "Yes" at the "Apply anyway", I'll see `1 out of 1 hunk FAILED`.

If I chose Yes at the first question, I'll see `1 out of 3 hunks FAILED`.

I tried to skip this process and continue the tutorial. It generated the firmware, but when I flashed it, the SSH was disabled.

**Comment by geekman** [comment]
Yeah sorry my bad. The patches are currently for the AX3600 and I haven't really figured out a proper system for other devices.

For now, just delete the `patches` folder and try again. Let me know if you still have any problems.

**Comment by gabriel-lando** [comment]
Hi, thanks :) It worked well
