### ISSUE TITLE
repack-squashfs.sh error script

### ISSUE THREAD

**Issue by lesadr** [geekman/xqrepack#24]
Hi,

I tried to run the script but unfortunately i have an error with the command on my Lubuntu (last version) computer.
It's about this command line :
fakeroot -- ./repack-squashfs.sh ubifs-root/miwifi_r3600_all_6510e_3.0.22_INT.bin/img-1135711824_vol-ubi_rootfs.ubifs

and the result :

/usr/bin/unsquashfs
unpacking squashfs...
Parallel unsquashfs: Using 4 processors
4305 inodes (4011 blocks) to write

[==========================================================================================================================================================================|] 8316/8316 100%

created 3847 files
created 251 directories
created 457 symlinks
created 1 device
created 0 fifos
created 0 sockets
created 0 hardlinks
patching squashfs...
applying patch patches/enable-iot-radio.patch...
1 out of 1 hunk FAILED -- saving rejects to file lib/wifi/qcawificfg80211.sh.rej

I tried to found the folder lib/wifi but it does exist ... i dont understand anything about this error, do you have any idea ?

Thx
Adrien

**Comment by geekman** [comment]
Looks like the international version for the AX3600 is different. To solve the error for now, please delete the entire `patches` folder and try again.

I'll take a look at the INT fw version later to see what's different when I have time.

**Comment by lesadr** [comment]
Thank you @geekman you resolve my issue, thank you so much !!!
Without the patchs files it's better for me.
Thank You !!! ^^
