### ISSUE TITLE
Works with Xiaomi AX6000

### ISSUE THREAD

**Issue by unocerobits** [geekman/xqrepack#25]
Following my [comment ](https://github.com/geekman/xqrepack/issues/19#issuecomment-1353805207). I have put the modified firmware in to the AX6000 (RA72) perfectly, updating "patch" files with 1.0.55 firmware version (SSH patched previously). In the first burned, I had a odd behaveral of Internet LED (always off), but in the next burned, it works perfectly.
Are you interested in include in to xqrepack?

**Comment by mrmaximas** [comment]
i'm interested with full instructions ;) thanks!

**Comment by geekman** [comment]
Hi @unocerobits I've just run the script on the AX6000 firmware and didn't seem to have any problems (aside from the wrong patches for AX3600 being applied onto AX6000). If you do have patches that are equivalent of those for AX3600, I'd welcome a PR. Thanks.

**Comment by unocerobits** [comment]
Perfect @geekman! 
I attach you the .patch files.
In my case, I created a little revision for AX6000, touching "Makefile, repack-squashfs.sh and ubinize.sh" and merging with [@pablocp19](https://github.com/pablocp19/xqrepack), great fork of your excelent work.

For AX6000, this files only work with the firmware `1.0.55`:

- [enable-iot-radio-AX6000.patch](https://github.com/geekman/xqrepack/files/10368389/enable-iot-radio-AX6000.patch)
- [hostapd_options-AX6000.patch](https://github.com/geekman/xqrepack/files/10368390/hostapd_options-AX6000.patch)

Best regards
