### ISSUE TITLE
[QUESTION] how to load r3600-raw-img.bin into AX3600

### ISSUE THREAD

**Issue by Dzmitry-Hrushetski** [geekman/xqrepack#4]
Hello, I'm making my own firmware based on your scripts. The firmware miwifi_r3600_all_6510e_3.0.22_INT.bin was taken as the basis.
I have corrected the qcawificfg80211.sh file to change the Wifi power.

The patch was successful, after rebooting the router, I connected to it via SSH with the old password, which was set when receiving SSH on firmware miwifi_r3600_firmware_5da25_1.0.17.
After doing a factory reset, I get the error
buntu @ ubuntu2010: ~ / Desktop $ ssh root@192.168.31.1
ssh: connect to host 192.168.31.1 port 22: Connection refused

ubuntu @ ubuntu2010: ~ / Desktop $ telnet 192.168.31.1
Trying 192.168.31.1 ...
telnet: Unable to connect to remote host: Connection refused

What could be the problem.
I am attaching my patch script.
[repack-my.zip](https://github.com/geekman/xqrepack/files/6004641/repack-my.zip)

**Comment by 1300371** [comment]
I'm facing similar problem.

1. I downgrade to 1.0.17
1. I patched miwifi_r3600_all_6510e_3.0.22_INT.bin firmware following instructions
1. I flashed the firmware and reboot
1. On reboot, 3.0.22 firmware but no more SSH

**Comment by Dzmitry-Hrushetski** [comment]
I have an idea.
After a reset, dropbear is initialized back to its original value.
Script command
  # modify dropbear init
sed -i 's / channel =. * / channel = release2 /' "$ FSDIR / etc / init.d / dropbear"

replaces the original string

channel = `/ sbin / uci get
  usr / share / xiaoqiang / xiaoqiang_version.version.CHANNEL`

I suppose that you also need to patch the file usr / share / xiaoqiang / xiaoqiang_version.version and replace the # channel option CHANNEL 'release' value with 'release2'

**Comment by Dzmitry-Hrushetski** [comment]
I found the following information.
https://oded.dev/2020/11/30/AX3600-1/

I think it is necessary to combine these two methods.

**Comment by 1300371** [comment]
> I found the following information.
> https://oded.dev/2020/11/30/AX3600-1/
> 
> I think it is necessary to combine these two methods.

I finally used this method to have INT firmware with SSH working

**Comment by geekman** [comment]
Thanks for bringing this issue to my attention! Until I can figure out what else is resetting the `ssh_en` variable, I would agree that a permanent solution to retaining SSH access is to modify `bdata`, which is read-only so that the firmware can't reset it back.

**Comment by geekman** [comment]
I have released a new version, which should fix SSH access: https://github.com/geekman/xqrepack/releases/tag/v1.1

Please let me know if this works for you.

**Comment by zsdd89** [comment]
Hi
Please could someone make a modified fw from miwifi_r3600_all_6510e_3.0.22_INT.bin version with the newest script? Im not a linux guru, i had problems with installing and using ubi reader
My bdata partition is already modified to CN region
Thank you

**Comment by zsdd89** [comment]
With the latest script the ssh is working again, thanks
